version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - apt-get update
      - java -version
      - mvn -version 

  pre_build:
    commands:
      - echo Running Maven Clean...
      - mvn clean

  build:
    commands:
      - echo Running Maven Build...
      - mvn compile

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/**/*
  discard-paths: yes
